name: CI
on:
  push:
    branches-ignore: [ incarnation ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - uses: actions/setup-node@v2.3.2

    - name: Init deps
      run: yarn --frozen-lockfile

    - name: Test
      run: yarn lint

    - name: Build
      run: yarn build
