name: CI
on:
    push:
        branches-ignore: [incarnation]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: nschloe/action-cached-lfs-checkout@v1

            - uses: actions/setup-node@v3.5.1

            - name: Init deps
              run: yarn --frozen-lockfile

            - name: Build
              run: yarn build

            - name: Test
              run: yarn lint
