name: CI
on:
  push:
    branches: [ incarnation ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - uses: actions/setup-node@v2.5.0

    - name: Init deps
      run: yarn --frozen-lockfile

    - name: Test
      run: yarn lint

    - name: Build
      run: yarn build

    - name: deploy to netlify
      # using cloudflare pages instead
      if: false
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      run: npx netlify-cli deploy --prod --dir=public
