name: CI
on:
    push:
        branches: [incarnation]
    pull_request:
        branches: [incarnation]

jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            deploy-url: ${{ steps.pages.outputs.url }}
        steps:
            - uses: nschloe/action-cached-lfs-checkout@v1

            - name: Prepare Node.js
              uses: actions/setup-node@v3.8.1
              with:
                  node-version-file: .node-version
                  cache: yarn

            - name: Init deps
              run: yarn install

            - name: Build
              run: yarn build

            - name: Lint
              run: yarn lint

            - id: pages
              name: Deploy to Cloudflare Pages
              uses: cloudflare/pages-action@v1
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  projectName: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
                  directory: public

    e2e:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: nschloe/action-cached-lfs-checkout@v1

            - name: Prepare Node.js
              uses: actions/setup-node@v3.8.1
              with:
                  node-version-file: .node-version
                  cache: yarn

            - run: yarn install
            - run: yarn playwright install --with-deps
            - name: Run Playwright tests
              env:
                  RESTIA_E2E_URL: ${{ needs.build.outputs.deploy-url }}
              run: yarn playwright test
            - uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 20
