name: CI
on:
    push:
        branches: [incarnation]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: nschloe/action-cached-lfs-checkout@v1

            - uses: actions/setup-node@v3.5.1

            - name: Init deps
              run: yarn --frozen-lockfile

            - name: Build
              run: yarn build

            - name: Test
              run: yarn lint

            - name: deploy to netlify
              # using cloudflare pages instead
              if: false
              env:
                  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
              run: npx netlify-cli deploy --prod --dir=public
